org: errkk
app: button-lambda
service: button-handler
component: aws-lambda

provider:
  name: aws
  runtime: python3.9
  timeout: 10

  stage: prod
  region: eu-west-2

  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'lambda:ListTags'
        - 'lambda:TagResource'
      Resource:
        - ${param:arn}

    - Effect: 'Allow'
      Action:
        - 'events:DisableRule'
        - 'events:EnableRule'
        - 'events:PutRule'
      Resource:
        - ${param:arn_rule}

  environment:
    arn: ${param:arn}
    arn_rule: ${param:arn_rule}
    hue_application_key: ${param:hue_application_key}
    hue_client_id: ${param:hue_client_id}
    hue_client_secret: ${param:hue_client_secret}
    sonos_client_id: ${param:sonos_client_id}
    sonos_client_secret: ${param:sonos_client_secret}
    sonos_household: ${param:sonos_household}
    hue_token_key: hueToken
    sonos_token_key: sonosToken
    prev_vol_key: previousVol

package:
  include:
    - v-env/lib/python3.8/site-packages/**
    - src/*
  exclude:
    - .env

plugins:
  - serverless-python-requirements
custom:
  pythonRequirements:
     dockerizePip: false
     pythonBin: python3

functions:
  main:
    handler: handler.main

  set_vol:
    handler: handler.set_vol
    events:
      - http:
          path: set_vol/{vol}
          method: put

  fade:
    handler: handler.fade
    timeout: 20
    events:
      - schedule:
          name: sleep-timer
          description: 'Sleep timer'
          enabled: false
          rate: cron(0 0 29 2 ? *)

  set_sleep:
    handler: handler.set_sleep
    events:
      - http:
          path: set_sleep/{mins}
          method: put

  cancel_sleep:
    handler: handler.cancel_sleep
    events:
      - http:
          path: set_sleep
          method: delete

  turn_down_ads:
    handler: handler.turn_down_ads
    events:
      - schedule:
          name: turn-down-ads
          description: 'Turn down vol on the hour for a couple of mins'
          enabled: true
          rate: cron(0 * * * ? *)

  on_ad_timeout:
    handler: handler.on_ad_timeout
    events:
      - schedule:
          name: on-ad-timeout 
          description: 'Turn vol back after the fucking ads'
          enabled: true
          rate: cron(5 * * * ? *)
